// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"database/sql"
	"week04/internal/dao"
	"week04/internal/service"
)

// Injectors from wire.go:

func InitializeDemo(db *sql.DB) *service.UserService {
	userDao := dao.NewUserDao(db)
	userService := service.NewUserService(userDao)
	return userService
}
